// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright 2026 Edgecast Cloud LLC.

//! A client for the cloud-image-index, generated by progenitor from the
//! OpenAPI document the index publishes (`v1/openapi.json`).
//!
//! Its types are generated from the document rather than taken from the
//! API crate, so the client depends on neither Dropshot nor its TLS
//! stack, and tolerates the index evolving as any generated client must
//! (see "Schema evolution" in docs/design.md).
//!
//! The base URL is the directory containing `v1/`, e.g.
//! `https://tritondatacenter.github.io/cloud-image-index`.

#[allow(
    clippy::all,
    clippy::unwrap_used,
    clippy::expect_used,
    rustdoc::all,
    missing_docs
)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/client.rs"));
}

pub use generated::*;
